### ISSUE TITLE
Not working when using Web Workers

### ISSUE THREAD

**Issue by tutq8118** [chrisbottin/xml-formatter#30] opened 2021-01-29 04:52 UTC
Hi there,

I imported the library in Web Worker, but it did not work

```javascript
importScripts("https://cdn.jsdelivr.net/npm/xml-formatter@2.4.0/dist/browser/xml-formatter.js");
````
```javascript
var formattedXml = format(formatArea, {
            indentation: "    ",
            filter: (node) => node.type !== "Comment",
            collapseContent: true,
            lineSeparator: "\n",
        });
```
Could you please help me!

Thank you,

**Comment by chrisbottin** [comment] 2021-02-01 15:48
Hi,

Can you explain what the problem is? ...Or post the error you're getting.

**Comment by chrisbottin** [comment] 2021-04-15 07:16
No enough information. Closing this issue

**Closed by chrisbottin** 2021-04-15 07:16 UTC
