### ISSUE TITLE
CDATA not being handled correctly

### ISSUE THREAD

**Issue by maxkreja** [chrisbottin/xml-formatter#11] opened 2019-11-05 10:30 UTC
If the XML contains a CDATA tag the formatter won't output the tag and any other XML tags after the CDATA tag.

Example Input:

```xml
<root><![CDATA[some text]]><child><subchild/></child></root>
```

Example Output:

```xml
<root>
</root>
```

Expected Output:

```xml
<root>
  <![CDATA[some text]]>
  <child>
    <subchild/>
  </child>
</root>
```

Info:
- Node.js: 12.13.0
- xml-formatter: 1.1.0

**Comment by maxkreja** [comment] 2019-11-13 08:25
Issue seems related to segmentio/xml-parser#25

**Comment by chrisbottin** [comment] 2019-11-14 09:18
Thanks for the information. I will provide a fix shortly but can't give you any timescale.

**Comment by chrisbottin** [comment] 2020-04-18 11:04
This should be fixed by #15

**Closed by chrisbottin** 2020-04-18 11:04 UTC

**Comment by sp53519** [comment] 2020-06-08 14:49
Checked in version 2.1.0. The problem is relevant.

**Comment by CatalinMustata** [comment] 2021-05-25 15:36
Works in 2.4.0
